version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation de l'image Java 8
    steps:
      - checkout  # Vérifie le code source
      - run:
          name: Set up Maven
          command: |
            echo "Maven is set up"
      - run:
          name: Build and run tests
          command: mvn clean test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Exécute uniquement sur la branche master
