version: 2.1

# Inclure l'orb Codecov certifié
orbs:
  codecov: codecov/codecov@3

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      # Construire le projet Maven sans exécuter les tests
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Exécuter les tests avec JaCoCo activé pour générer un rapport de couverture
      - run:
          name: Test and Generate Coverage Report
          command: mvn test jacoco:report

      # Sauvegarder les fichiers nécessaires pour Codecov
      - persist_to_workspace:
          root: .
          paths:
            - target/site/jacoco
            - target

  # Job pour uploader sur Codecov
  upload-to-codecov:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout  # Cette étape est nécessaire pour obtenir le code avant d'envoyer les rapports
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build-and-test
      - upload-to-codecov:
          requires:
            - build-and-test
